### ISSUE TITLE
whois command should support tagging

### ISSUE THREAD

**Issue by Malivil** [Hawkpath/sandpiper#22]
Currently when using "!piper whois" you have to type a name manually e.g. "!piper whois Malivil"
It would be nice to be able to do "!piper whois @Malivil" to take advantage of the auto-complete

**Comment by Malivil** [comment]
The code looks like it does a lookup by username, so maybe it just needs to strip the "@" at the beginning? I don't have the DB setup to test.

**Comment by Hawkpath** [comment]
I actually deliberately decided against this while programming sandpiper because I don't want to encourage people pinging others for bot commands. It annoys me when other bots force you to do this. I'm open to discussion about it, though.

**Comment by Malivil** [comment]
I'm fine with that reasoning but maybe report that back as the error message rather than "user not found"

**Comment by Hawkpath** [comment]
That sounds like a good solution! I didn't realize it did that.
