### ISSUE TITLE
Add support for yards in unit conversion

### ISSUE THREAD

**Issue by Malivil** [Hawkpath/sandpiper#24]
geoguessr uses yards sometimes and people get confused

**Comment by Hawkpath** [comment]
I'm learning to stop thinking "who will even use this" because there's almost always a reason 😂

**Comment by Malivil** [comment]
I'm looking into seeing if I can do this myself but I can't find where in the pint documentation the list of supported units is

**Comment by Hawkpath** [comment]
To do this I need to rethink about the current unit conversion bidict interface. Right now, each unit conversion is a two-way link with only one unit on each side. Adding yards will make it `meter <-> (feet, yard)`, and I don't want it to show both yards and feet every time.

Solution:
- Retain two-way link `meter <-> feet`
- Add one-way link `yard -> meter`
- Related to #11, add a format specifier to allow `meter -> yard`

**Comment by Hawkpath** [comment]
> 
> 
> I'm looking into seeing if I can do this myself but I can't find where in the pint documentation the list of supported units is

I'm actually already working on Sandpiper atm so I can work on this real quick.

**Comment by Malivil** [comment]
Ok, all yours =)

**Comment by Malivil** [comment]
I think that yards->meter is probably more useful than m>yd
